default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  # password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  # host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  # port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  url: postgres://ffdafdsfasd_user:UVQtTrsYPNTrH3Jm0fJHbgoAY8Czew4F@dpg-cp6qj7mv3ddc73folh9g-a.oregon-postgres.render.com/ffdafdsfasd

# test:
#   <<: *default
#   database: rails_api_base_test<%= ENV['TEST_ENV_NUMBER'] %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
# production:
#   <<: *default
